name: Merge to Master

on:
  pull_request:
    branches: 
        - develop
    types: [closed]

jobs:
  merge_to_master:
    if: github.event.pull_request.merged
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create pull request to master
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: develop
        title: 'Merge develop into master'
        body: 'This pull request was automatically created when merging develop into master.'
