name: Push to main

on:
  push:
    branches:
      - develop

jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2   # Checkout develop branch again (avoid credential issues)
        with:
          ref: ${{ github.sha }}  # Use the pushed commit SHA
      - run: |
          git config --global user.email "ozyparkar@gmail.com"
          git config --global user.name "UsamaParkar"
          git push origin ${{ github.sha }} master  # Push to main with PAT
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Personal Access Token with push access
